# Generated by Django 3.2.8 on 2021-10-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorldHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000, verbose_name='Сұрақ')),
                ('answer', models.CharField(max_length=1000, verbose_name='Жауабы')),
            ],
            options={
                'verbose_name': 'Дүниежүзі тарихы',
                'verbose_name_plural': 'Дүниежүзі тарихы',
            },
        ),
    ]
