# Generated by Django 3.2.8 on 2021-11-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000, verbose_name='Сұрақ')),
                ('answer', models.CharField(max_length=1000, verbose_name='Жауабы')),
            ],
            options={
                'verbose_name': 'Физика',
                'verbose_name_plural': 'Физика',
            },
        ),
    ]
