# Generated by Django 3.2.8 on 2022-02-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_physic'),
    ]

    operations = [
        migrations.CreateModel(
            name='QazaqstanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Сұрақ')),
                ('answer_true', models.CharField(max_length=100, verbose_name='Жауабы (Дұрыс)')),
                ('answer_false_1', models.CharField(max_length=100, verbose_name='Жауабы (Бұрыс)')),
                ('answer_false_2', models.CharField(max_length=100, verbose_name='Жауабы (Бұрыс)')),
                ('answer_false_3', models.CharField(max_length=100, verbose_name='Жауабы (Бұрыс)')),
            ],
            options={
                'verbose_name': 'Қазақстан тарихы (Pro)',
                'verbose_name_plural': 'Қазақстан тарихы (Pro)',
            },
        ),
    ]
