# Generated by Django 3.2.8 on 2021-10-28 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_day', models.IntegerField(verbose_name='Туылған күні')),
                ('birth_mounth', models.IntegerField(verbose_name='Туылған айы')),
                ('birth_year', models.IntegerField(verbose_name='Туылған жылы')),
                ('profile_photo', models.TextField(verbose_name='Сурет (Base 64) ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
