# Generated by Django 3.2.8 on 2021-11-09 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0003_customer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_all', models.IntegerField(verbose_name='Жалпы сұрақ')),
                ('result_true', models.IntegerField(verbose_name='Қате сұрақ')),
                ('result_false', models.IntegerField(verbose_name='Дұрыс сұрақ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
