# Generated by Django 3.2.8 on 2021-11-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='prduct_type',
            field=models.CharField(choices=[('Қазақстан тарихы', 'Қазақстан тарихы'), ('Дүниежүзі тарихы', 'Дүниежүзі тарихы')], default='Қазақстан тарихы', max_length=50, verbose_name='Тип заказа'),
        ),
    ]
