# Generated by Django 3.2.8 on 2021-11-10 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_userprogress_prduct_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprogress',
            old_name='prduct_type',
            new_name='course',
        ),
    ]
